spring.application.name=currency-service
server.port=8100

spring.datasource.url=jdbc:postgresql://localhost:5432/db_currency
spring.datasource.username=postgres
spring.datasource.password=teste

#Já tem o banco, ent n precisa criar
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:db_migration

#SelfRegistrationPattern
eureka.client.service-url.default-zone=http://localhost8761/eureka

#Ideal para ambiente conteinerzado
eureka.instance.prefer-ip-address=true
#Indicar que o Service Register deve validar a saúde do serviço através do actuator e n só hearthbeat(opcional - default true)
eureka.client.healthcheck.enabled=true
#Personaliza o ip
eureka.instance.instance-id=${spring.application.name}:${server.port}

#Configuração mínima para atuação com o Service Register de forma consciente
management.endpoints.web.exposure.include=health,info, metrics
management.endpoint.health.show-details=always
#Exibir informações no /actuator/info
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=João Gabriel Winck Mendes
#Pesonalização de Metadata para o Eureka Service Registery
eureka.instance.metadata-map.github.repo=JoaoGabrielWMendes/microservices-java

