spring.application.name=greeting-services
server.port=8080

greeting-service.greeting=Ola
greeting-service.default-name=Mundo

spring.profiles.active=fr

management.endpoints.web.exposure.include=*
#sempre cuidar ao exibir isso, informação SENSIVEL, usado assim só pra fins didáticos
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8888/
#optional pois vai rodar a aplicação mesmo que o server esteja off