spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=true

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events

info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=João Gabriel Winck Mendes
#Pesonalização de Metadata para o Eureka Service Registery
eureka.instance.metadata-map.github.repo=JoaoGabrielWMendes/microservices-java